### PR TITLE
Adds ability to swap audio channels from a config file.

### PR DESCRIPTION
**Pull request by philippReist**

### CODE REVIEW

**Comment by r-oung** [comment]
@philippReist I tested this on Ubuntu and it works as intended. I'll try on a macOS later. Is is possible to create a unit test for this?

**Comment by philippReist** [comment]
Thank you, Ray! Yes I can unit test this.

@tiemes what is the time line for you to start using this feature?

**Comment by tiemes** [comment]
@philippReist due to covid-19 we'll not host any workshops before February for sure. We aim to start again in March.

**Comment by philippReist** [comment]
@r-oung : I added the audio channel swapping UT and rebased on your MR.

We should bump the minor so this will be v1.1.0.

I will do a functionality test (with 5.12.9) now and then I think we are ready to merge back.

**Pull request merged**
